steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'gcloud compute instances start arm64-build-instance --zone=us-central1-a'

  # make sure the instance is up and running
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'gcloud compute instances describe arm64-build-instance --zone=us-central1-a --format="yaml(name,status)"'

  - name: 'gcr.io/cloud-builders/git'
    id: 'setup-ssh'
    secretEnv: ['ARM_BUILDER_SSH_KEY', 'ARM64_MACHINE_IP']
    entrypoint: 'bash'
    args:
    - -c
    - |
      echo "writing key"
      echo "$$ARM_BUILDER_SSH_KEY" >> /root/.ssh/ci-bot
      echo "modifying key permissions"
      chmod 400 /root/.ssh/ci-bot
      echo "adding key to ssh agent"
      ssh-keyscan -t rsa $$ARM64_MACHINE_IP > /root/.ssh/known_hosts
      echo "ssh setup complete"
      sleep 60
    volumes:
    - name: 'ssh'
      path: /root/.ssh

  - name: gcr.io/cloud-builders/docker
    waitFor: ['setup-ssh']
    entrypoint: "bash"
    args: ["-c", "./devops/build.sh;"]
    env: 
    - 'REPO_NAME=$REPO_NAME'
    - 'BRANCH_NAME=$BRANCH_NAME'      
    - 'BUILD_ARCHITECTURE=amd'
    - 'GCLOUD_BUILD=true'
    - 'GIT_DISCOVERY_ACROSS_FILESYSTEM=1'
    secretEnv: ['ARM64_MACHINE_IP']
    volumes:
    - name: 'ssh'
      path: /root/.ssh

  - name: gcr.io/cloud-builders/docker
    waitFor: ['setup-ssh']
    entrypoint: "bash"
    args: ["-c", "./devops/build.sh;"]
    env: 
    - 'REPO_NAME=$REPO_NAME'
    - 'BRANCH_NAME=$BRANCH_NAME'      
    - 'BUILD_ARCHITECTURE=arm'
    - 'GCLOUD_BUILD=true'
    - 'GIT_DISCOVERY_ACROSS_FILESYSTEM=1'
    secretEnv: ['ARM64_MACHINE_IP']
    volumes:
    - name: 'ssh'
      path: /root/.ssh

  - name: gcr.io/cloud-builders/docker
    entrypoint: "bash"
    args: ["-c", "./devops/create-manifest.sh"]
    env: 
      - 'GCLOUD_BUILD=true'
      - 'GIT_DISCOVERY_ACROSS_FILESYSTEM=1'
      - 'SHORT_SHA=$SHORT_SHA'
      - 'TAG_NAME=$TAG_NAME'
      - 'BRANCH_NAME=$BRANCH_NAME'


options:
  pool:
    name: projects/digital-ucdavis-edu/locations/us-central1/workerPools/ucd-lib-arm-builds

availableSecrets:
  secretManager:
  - versionName: projects/digital-ucdavis-edu/secrets/arm64-builder-ci-bot-ssh-key/versions/latest
    env: 'ARM_BUILDER_SSH_KEY'
  - versionName: projects/digital-ucdavis-edu/secrets/arm64-builder-ip/versions/latest
    env: 'ARM64_MACHINE_IP'

timeout: 1800s