steps:

  - name: gcr.io/cloud-builders/docker
    entrypoint: "bash"
    args: ["-c", "./devops/pull.sh"]
    env:
    - 'REPO_NAME=$REPO_NAME'
    - 'BRANCH_NAME=$BRANCH_NAME'

  - name: gcr.io/cloud-builders/docker
    entrypoint: "bash"
    args: ["-c", "./devops/build.sh;"]
    env: 
    - 'REPO_NAME=$REPO_NAME'
    - 'BRANCH_NAME=$BRANCH_NAME'

  - name: gcr.io/cloud-builders/docker
    entrypoint: "bash"
    args: ["-c", "./devops/push.sh"]
    env:
    - 'REPO_NAME=$REPO_NAME'
    - 'BRANCH_NAME=$BRANCH_NAME'

timeout: 1800s